# Data Pre-Processing

In [97]:
import pandas as pd
import os
from pathlib import Path

In [99]:
BASE_DIRECTORY = Path("D:/CIC IoT 2023/archive/wataiData/")
DATASET_DIRECTORY = BASE_DIRECTORY / "csv" / "CICIoT2023"
CLEANED_DIRECTORY = BASE_DIRECTORY / "csv" / "CleanedDataframes"
PARQUET_DIRECTORY = BASE_DIRECTORY / "parquet"
SCALED_DIRECTORY = BASE_DIRECTORY / "scaled"
FINAL_DIRECTORY = BASE_DIRECTORY / "final"

os.makedirs(CLEANED_DIRECTORY, exist_ok=True)
os.makedirs(PARQUET_DIRECTORY, exist_ok= True)
os.makedirs(SCALED_DIRECTORY, exist_ok= True)
os.makedirs(FINAL_DIRECTORY, exist_ok= True)

In [101]:
dataframes = [x for x in os.listdir(DATASET_DIRECTORY) if x.endswith(".csv")]

In [103]:
dataframes

['part-00000-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00001-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00002-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00003-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00004-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00005-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00006-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00007-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00008-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00009-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00010-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00011-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00012-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00013-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00014-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00015-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00016-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00017-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00018-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00019-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00020-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00021-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00022-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00023-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00024-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00025-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00026-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00027-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00028-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00029-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00030-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00031-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00032-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00033-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00034-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00035-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00036-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00037-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00038-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00039-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00040-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00041-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00042-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00043-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00044-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00045-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00046-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00047-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00048-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00049-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00050-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00051-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00052-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00053-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00054-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00055-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00056-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00057-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00058-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00059-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00060-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00061-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00062-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00063-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00064-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00065-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00066-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00067-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00068-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00069-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00070-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00071-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00072-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00073-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00074-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00075-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00076-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00077-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00078-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00079-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00080-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00081-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00082-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00083-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00084-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00085-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00086-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00087-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00088-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00089-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00090-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00091-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00092-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00093-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00094-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00095-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00096-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00097-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00098-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00099-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00100-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00101-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00102-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00103-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00104-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00105-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00106-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00107-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00108-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00109-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00110-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00111-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00112-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00113-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00114-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00115-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00116-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00117-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00118-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00119-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00120-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00121-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00122-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00123-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00124-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00125-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00126-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00127-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00128-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00129-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00130-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00131-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00132-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00133-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00134-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00135-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00136-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00137-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00138-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00139-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00140-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00141-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00142-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00143-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00144-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00145-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00146-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00147-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00148-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00149-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00150-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00151-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00152-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00153-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00154-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00155-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00156-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00157-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00158-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00159-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00160-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00161-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00162-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00163-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00164-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00165-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00166-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00167-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv',
 'part-00168-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv']

## General check on one of the dataframes so i get to know how to handle their cleaning process

In [106]:
path = os.path.join(DATASET_DIRECTORY, dataframes[0])
test_df = pd.read_csv(path)
test_df

,flow_duration,Header_Length,Protocol Type,Duration,Rate,Srate,Drate,fin_flag_number,syn_flag_number,rst_flag_number,...,Std,Tot size,IAT,Number,Magnitue,Radius,Covariance,Variance,Weight,label
0,0.000000,54.00,6.00,64.00,0.329807,0.329807,0.0,1.0,0.0,1.0,...,0.000000,54.00,8.334383e+07,9.5,10.392305,0.000000,0.000000,0.00,141.55,DDoS-RSTFINFlood
1,0.000000,57.04,6.33,64.00,4.290556,4.290556,0.0,0.0,0.0,0.0,...,2.822973,57.04,8.292607e+07,9.5,10.464666,4.010353,160.987842,0.05,141.55,DoS-TCP_Flood
2,0.000000,0.00,1.00,64.00,33.396799,33.396799,0.0,0.0,0.0,0.0,...,0.000000,42.00,8.312799e+07,9.5,9.165151,0.000000,0.000000,0.00,141.55,DDoS-ICMP_Flood
3,0.328175,76175.00,17.00,64.00,4642.133010,4642.133010,0.0,0.0,0.0,0.0,...,0.000000,50.00,8.301570e+07,9.5,10.000000,0.000000,0.000000,0.00,141.55,DoS-UDP_Flood
4,0.117320,101.73,6.11,65.91,6.202211,6.202211,0.0,0.0,1.0,0.0,...,23.113111,57.88,8.297300e+07,9.5,11.346876,32.716243,3016.808286,0.19,141.55,DoS-SYN_Flood
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238682,0.000000,54.00,6.00,64.00,3.049186,3.049186,0.0,1.0,0.0,1.0,...,0.000000,54.00,8.334449e+07,9.5,10.392305,0.000000,0.000000,0.00,141.55,DDoS-RSTFINFlood
238683,0.000000,54.00,6.00,64.00,183.433732,183.433732,0.0,0.0,0.0,0.0,...,0.000000,54.00,8.331392e+07,9.5,10.392305,0.000000,0.000000,0.00,141.55,DDoS-PSHACK_Flood
238684,0.000785,56.29,6.11,64.00,306.952216,306.952216,0.0,0.0,1.0,0.0,...,0.140764,54.21,8.308883e+07,9.5,10.395538,0.200659,0.671167,0.03,141.55,DDoS-SYN_Flood
238685,0.000901,72.09,6.11,64.64,158.475986,158.475986,0.0,0.0,0.0,0.0,...,2.450404,55.48,8.333177e+07,9.5,10.456522,3.475801,55.994224,0.17,141.55,DDoS-PSHACK_Flood
238686,0.000000,0.00,1.00,64.00,1.291274,1.291274,0.0,0.0,0.0,0.0,...,0.000000,42.00,8.312453e+07,9.5,9.165151,0.000000,0.000000,0.00,141.55,DDoS-ICMP_Flood

In [107]:
test_df.dtypes

flow_duration      float64
Header_Length      float64
Protocol Type      float64
Duration           float64
Rate               float64
Srate              float64
Drate              float64
fin_flag_number    float64
syn_flag_number    float64
rst_flag_number    float64
psh_flag_number    float64
ack_flag_number    float64
ece_flag_number    float64
cwr_flag_number    float64
ack_count          float64
syn_count          float64
fin_count          float64
urg_count          float64
rst_count          float64
HTTP               float64
HTTPS              float64
DNS                float64
Telnet             float64
SMTP               float64
SSH                float64
IRC                float64
TCP                float64
UDP                float64
DHCP               float64
ARP                float64
ICMP               float64
IPv                float64
LLC                float64
Tot sum            float64
Min                float64
Max                float64
AVG                float64
Std                float64
Tot size           float64
IAT                float64
Number             float64
Magnitue           float64
Radius             float64
Covariance         float64
Variance           float64
Weight             float64
label               object
dtype: object

In [110]:
test_df["ack_count"]

0         1.00
1         0.00
2         0.00
3         0.00
4         0.00
          ...
238682    1.00
238683    0.00
238684    0.00
238685    0.02
238686    0.00
Name: ack_count, Length: 238687, dtype: float64

In [112]:
test_df["ece_flag_number"].unique()

array([0.])

In [114]:
test_df.isnull().any()

flow_duration      False
Header_Length      False
Protocol Type      False
Duration           False
Rate               False
Srate              False
Drate              False
fin_flag_number    False
syn_flag_number    False
rst_flag_number    False
psh_flag_number    False
ack_flag_number    False
ece_flag_number    False
cwr_flag_number    False
ack_count          False
syn_count          False
fin_count          False
urg_count          False
rst_count          False
HTTP               False
HTTPS              False
DNS                False
Telnet             False
SMTP               False
SSH                False
IRC                False
TCP                False
UDP                False
DHCP               False
ARP                False
ICMP               False
IPv                False
LLC                False
Tot sum            False
Min                False
Max                False
AVG                False
Std                False
Tot size           False
IAT                False
Number             False
Magnitue           False
Radius             False
Covariance         False
Variance           False
Weight             False
label              False
dtype: bool

In [116]:
test_df['label'].unique()

array(['DDoS-RSTFINFlood', 'DoS-TCP_Flood', 'DDoS-ICMP_Flood',
       'DoS-UDP_Flood', 'DoS-SYN_Flood', 'Mirai-greeth_flood',
       'DDoS-SynonymousIP_Flood', 'Mirai-udpplain', 'DDoS-SYN_Flood',
       'DDoS-PSHACK_Flood', 'DDoS-TCP_Flood', 'DDoS-UDP_Flood',
       'BenignTraffic', 'MITM-ArpSpoofing', 'DDoS-ACK_Fragmentation',
       'Mirai-greip_flood', 'DoS-HTTP_Flood', 'DDoS-ICMP_Fragmentation',
       'Recon-PortScan', 'DNS_Spoofing', 'DDoS-UDP_Fragmentation',
       'Recon-OSScan', 'XSS', 'DDoS-HTTP_Flood', 'Recon-HostDiscovery',
       'CommandInjection', 'VulnerabilityScan', 'DDoS-SlowLoris',
       'Backdoor_Malware', 'BrowserHijacking', 'DictionaryBruteForce',
       'SqlInjection', 'Recon-PingSweep', 'Uploading_Attack'],
      dtype=object)

In [118]:
test_df['HTTP'].unique()

array([0., 1.])

# Actual Pre-Processing
##### Step-1: drop null valies (missing values), transform datatypes and encode categorical variables

In [39]:
import numpy as np

for file in dataframes:
    # Getting the file path and reading it (one by one)
    path = os.path.join(DATASET_DIRECTORY, file)
    dataframe = pd.read_csv(path)

    # Dropping null values if they exist (dropping cuz if null values exist, they wont affect the data since it has over 30 million rows combined)
    dataframe.dropna(inplace= True)

    # Now im handling the data types (the flags must be binary, the counts must be integers {easier to deal with in the background than float})
    #First flags (Must be binary)
    flag_columns = ["fin_flag_number", "syn_flag_number", "rst_flag_number", "psh_flag_number", "ack_flag_number", "ece_flag_number", "cwr_flag_number"]
    for column in flag_columns:
        # Transforming them into True and False then -> 1 , 0 respectfully. (if greater than 0 then true, if not then false); because there might be higher numbers than 1
        dataframe[column] = (dataframe[column] > 0).astype("int8")

    # Second, Protocols datatypes (must be binary)
    protocol_columns = ["HTTP", "HTTPS", "DNS", "Telnet", "SMTP", "SSH", "IRC", "TCP", "UDP", "DHCP", "ARP", "ICMP", "IPv", "LLC"]
    for column in protocol_columns:
        dataframe[column] = dataframe[column].astype("int8")

    # Now encoding process (labels must be handled with label encoding {we dont wanna enlargen our features} )
    dataframe["label"] = dataframe["label"].astype("category").cat.codes

    # Save the processed dataframe to combine them all later
    out_path = os.path.join(CLEANED_DIRECTORY, file)
    dataframe.to_csv(out_path, index= False)

##### Step-2: Convert all cleaned files from csv format to parquet before scaling & outliers detection (for faster and safer computing and modeling later on as well)

###### We only RUN THE BELOW CHUNK ONCE (NO NEED TO DO IT TWICE, since the directory is stored on our disks)

In [37]:
for file in os.listdir(CLEANED_DIRECTORY):
    #going through everyfile (cleaned csv) by getting their path first
    csv_path = os.path.join(CLEANED_DIRECTORY, file)
    dataframe = pd.read_csv(csv_path)
    #convert the csv file into parquet and moving them to the correct directory (PARQUET_DIRECTORY)
    parquet_path = os.path.join(PARQUET_DIRECTORY, file.replace(".csv", ".parquet"))
    dataframe.to_parquet(parquet_path, index= False)

In [120]:
test_file = os.listdir(PARQUET_DIRECTORY)[0] # only first file (just for scanning purposess)
test_path = os.path.join(PARQUET_DIRECTORY, test_file)
test_df_parquet = pd.read_parquet(test_path)
test_df_parquet

,flow_duration,Header_Length,Protocol Type,Duration,Rate,Srate,Drate,fin_flag_number,syn_flag_number,rst_flag_number,...,Std,Tot size,IAT,Number,Magnitue,Radius,Covariance,Variance,Weight,label
0,0.000000,54.00,6.00,64.00,0.329807,0.329807,0.0,1,0,1,...,0.000000,54.00,8.334383e+07,9.5,10.392305,0.000000,0.000000,0.00,141.55,9
1,0.000000,57.04,6.33,64.00,4.290556,4.290556,0.0,0,0,0,...,2.822973,57.04,8.292607e+07,9.5,10.464666,4.010353,160.987842,0.05,141.55,20
2,0.000000,0.00,1.00,64.00,33.396799,33.396799,0.0,0,0,0,...,0.000000,42.00,8.312799e+07,9.5,9.165151,0.000000,0.000000,0.00,141.55,6
3,0.328175,76175.00,17.00,64.00,4642.133010,4642.133010,0.0,0,0,0,...,0.000000,50.00,8.301570e+07,9.5,10.000000,0.000000,0.000000,0.00,141.55,21
4,0.117320,101.73,6.11,65.91,6.202211,6.202211,0.0,0,1,0,...,23.113111,57.88,8.297300e+07,9.5,11.346876,32.716243,3016.808286,0.19,141.55,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238682,0.000000,54.00,6.00,64.00,3.049186,3.049186,0.0,1,0,1,...,0.000000,54.00,8.334449e+07,9.5,10.392305,0.000000,0.000000,0.00,141.55,9
238683,0.000000,54.00,6.00,64.00,183.433732,183.433732,0.0,0,0,0,...,0.000000,54.00,8.331392e+07,9.5,10.392305,0.000000,0.000000,0.00,141.55,8
238684,0.000785,56.29,6.11,64.00,306.952216,306.952216,0.0,0,1,0,...,0.140764,54.21,8.308883e+07,9.5,10.395538,0.200659,0.671167,0.03,141.55,10
238685,0.000901,72.09,6.11,64.64,158.475986,158.475986,0.0,0,0,0,...,2.450404,55.48,8.333177e+07,9.5,10.456522,3.475801,55.994224,0.17,141.55,8
238686,0.000000,0.00,1.00,64.00,1.291274,1.291274,0.0,0,0,0,...,0.000000,42.00,8.312453e+07,9.5,9.165151,0.000000,0.000000,0.00,141.55,6

##### Step-3: Scaling

In [123]:
#Before scaling, i must identitfy first the numerical columns (no target column like the (label) column ) and chehck the features to know what to scale
test_df_parquet.dtypes.unique()

array([dtype('float64'), dtype('int64')], dtype=object)

###### FIRST, exclude the label column (feature)

In [16]:
numerical_columns = test_df_parquet.select_dtypes(include=["float64", "int64"]).columns.tolist()
numerical_columns.remove("label")

###### Now, the binary features (Protocols, flags)

In [24]:
flag_columns = [ "fin_flag_number", "syn_flag_number", "rst_flag_number", "psh_flag_number", "ack_flag_number", "ece_flag_number", "cwr_flag_number"]
protocol_columns = ["HTTP", "HTTPS", "DNS", "Telnet", "SMTP", "SSH", "IRC", "TCP", "UDP", "DHCP", "ARP", "ICMP", "IPv", "LLC"]
binary_columns = flag_columns + protocol_columns

#now i remove the binary columns from the numerical_columns that im gonna scale
for col in binary_columns:
    if col in numerical_columns:
        numerical_columns.remove(col)

In [26]:
numerical_columns

['flow_duration',
 'Header_Length',
 'Protocol Type',
 'Duration',
 'Rate',
 'Srate',
 'Drate',
 'ack_count',
 'syn_count',
 'fin_count',
 'urg_count',
 'rst_count',
 'Tot sum',
 'Min',
 'Max',
 'AVG',
 'Std',
 'Tot size',
 'IAT',
 'Number',
 'Magnitue',
 'Radius',
 'Covariance',
 'Variance',
 'Weight']

In [30]:
test_df_parquet["Protocol Type"].unique()

array([ 6.  ,  6.33,  1.  , ...,  5.61,  0.  , 13.11])

In [34]:
#Scaling this feature (Protocol Type) should be okay since it is oringally float and it probably shows & has magnitude

#### The Actual Scaling now (I'll perform StandardScaler)

In [38]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
for file in os.listdir(PARQUET_DIRECTORY):
    path = os.path.join(PARQUET_DIRECTORY, file)
    dataframe = pd.read_parquet(path)
    # I dont wanna load everything into memory so im using partial_fit instead of fit
    std_scaler.partial_fit(dataframe[numerical_columns])

In [40]:
#Now last and final stage is to apply the scaling and save them
for file in os.listdir(PARQUET_DIRECTORY):
    #reading the files
    path = os.path.join(PARQUET_DIRECTORY, file)
    dataframe = pd.read_parquet(path)

    #applying the scaling
    dataframe[numerical_columns] = std_scaler.transform(dataframe[numerical_columns])

    #Saving the scaled files in the prevously made directory (SCALED_DIRECOTRY)
    destination_path = os.path.join(SCALED_DIRECTORY, file)
    dataframe.to_parquet(destination_path, index=False)

##### Checking the scaling results

In [50]:
file = os.listdir(SCALED_DIRECTORY)[0]
path = os.path.join(SCALED_DIRECTORY, file)
test_scaled_dataframe = pd.read_parquet(path)
test_scaled_dataframe.head()

,flow_duration,Header_Length,Protocol Type,Duration,Rate,Srate,Drate,fin_flag_number,syn_flag_number,rst_flag_number,...,Std,Tot size,IAT,Number,Magnitue,Radius,Covariance,Variance,Weight,label
0,-0.020227,-0.166154,-0.342706,-0.167679,-0.091036,-0.091036,-0.000754,1,0,1,...,-0.207844,-0.292659,0.009462,0.001844,-0.316334,-0.207678,-0.094913,-0.413894,0.001786,9
1,-0.020227,-0.166147,-0.305816,-0.167679,-0.090996,-0.090996,-0.000754,0,0,0,...,-0.190237,-0.280073,-0.015044,0.001844,-0.307948,-0.189993,-0.094416,-0.199302,0.001786,20
2,-0.020227,-0.166271,-0.901644,-0.167679,-0.090703,-0.090703,-0.000754,0,0,0,...,-0.207844,-0.342338,-0.003199,0.001844,-0.458554,-0.207678,-0.094913,-0.413894,0.001786,6
3,-0.019076,-0.001151,0.886958,-0.167679,-0.044414,-0.044414,-0.000754,0,0,0,...,-0.207844,-0.309219,-0.009786,0.001844,-0.361800,-0.207678,-0.094913,-0.413894,0.001786,21
4,-0.019816,-0.166050,-0.330410,-0.031437,-0.090977,-0.090977,-0.000754,0,1,0,...,-0.063689,-0.276596,-0.012291,0.001844,-0.205705,-0.063407,-0.085594,0.401554,0.001786,19

In [59]:
test_scaled_dataframe[flag_columns]

,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,cwr_flag_number
0,1,0,1,0,0,0,0
1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...
238682,1,0,1,0,0,0,0
238683,0,0,0,1,1,0,0
238684,0,1,0,0,0,0,0
238685,0,0,0,1,1,0,0
238686,0,0,0,0,0,0,0

In [61]:
test_scaled_dataframe[protocol_columns]

,HTTP,HTTPS,DNS,Telnet,SMTP,SSH,IRC,TCP,UDP,DHCP,ARP,ICMP,IPv,LLC
0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
1,1,0,0,0,0,0,0,1,0,0,0,0,1,1
2,0,0,0,0,0,0,0,0,0,0,0,1,1,1
3,0,0,0,0,0,0,0,0,1,0,0,0,1,1
4,0,0,0,0,0,0,0,1,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238682,0,0,0,0,0,0,0,1,0,0,0,0,1,1
238683,0,0,0,0,0,0,0,1,0,0,0,0,1,1
238684,0,0,0,0,0,0,0,1,0,0,0,0,1,1
238685,0,0,0,0,0,0,0,1,0,0,0,0,1,1
238686,0,0,0,0,0,0,0,0,0,0,0,1,1,1

##### Step-4: Handling Outliers

##### We cannot delete any data points because outliers in this specefic dataset are attacks, so we should instead clip them using percentiles
###### Which basically mean that we are shrnking the extreme datapoints and bringing them closer to the lower and upper bounderies (and these bounderies will be calculated for all 169 files and then we get their average) which are called global bounderies 
<span style="color:red">We should only use the numerical columns and never touch the label and the binary features; because they are continous values unlike the binary, which is only a classification, same for the label (target column)</span>

In [125]:
lower_bound = None
upper_bound = None
files_count = 0

files = os.listdir(SCALED_DIRECTORY)
for file in files:
    #loading the data (one by one)
    path = os.path.join(SCALED_DIRECTORY, file)
    dataframe = pd.read_parquet(path)

    lower_quantile = dataframe[numerical_columns].quantile(0.01)
    upper_quantile = dataframe[numerical_columns].quantile(0.99)

    #if its the first iteration, then just set the lower_bound to the lower_quantile and same for upper, otherwise, add them up
    if(lower_bound is None):
        lower_bound = lower_quantile
        upper_bound = upper_quantile
    else:
        lower_bound += lower_quantile
        upper_bound += upper_quantile
        
    files_count += 1

lower_bound = lower_bound / files_count
upper_bound = upper_bound

In [126]:
lower_bound.head()

flow_duration   -0.020227
Header_Length   -0.166271
Protocol Type   -0.902762
Duration        -0.268797
Rate            -0.091039
Name: 0.01, dtype: float64

In [127]:
upper_bound.head()

flow_duration     34.250863
Header_Length    799.858867
Protocol Type    716.659201
Duration         872.140347
Rate             193.530989
Name: 0.99, dtype: float64

##### Clipping application

In [129]:
# Clipping loop
files = os.listdir(SCALED_DIRECTORY)
for file in files:
    path = os.path.join(SCALED_DIRECTORY, file)
    dataframe = pd.read_parquet(path)

    #Clipping
    dataframe[numerical_columns] = dataframe[numerical_columns].clip(lower= lower_bound, upper= upper_bound, axis=1)

    #saving the final pre-processed files in the FINAL_DIRECTORY
    destination_path = os.path.join(FINAL_DIRECTORY, file)
    dataframe.to_parquet(destination_path, index= False)

In [130]:
file = os.listdir(FINAL_DIRECTORY)[0]
path = os.path.join(FINAL_DIRECTORY, file)
processed_df = pd.read_parquet(path)
processed_df.head()

,flow_duration,Header_Length,Protocol Type,Duration,Rate,Srate,Drate,fin_flag_number,syn_flag_number,rst_flag_number,...,Std,Tot size,IAT,Number,Magnitue,Radius,Covariance,Variance,Weight,label
0,-0.020227,-0.166154,-0.342706,-0.167679,-0.091036,-0.091036,-0.127353,1,0,1,...,-0.207844,-0.292659,0.009462,0.001844,-0.316334,-0.207678,-0.094913,-0.413894,0.001786,9
1,-0.020227,-0.166147,-0.305816,-0.167679,-0.090996,-0.090996,-0.127353,0,0,0,...,-0.190237,-0.280073,-0.015044,0.001844,-0.307948,-0.189993,-0.094416,-0.199302,0.001786,20
2,-0.020227,-0.166271,-0.901644,-0.167679,-0.090703,-0.090703,-0.127353,0,0,0,...,-0.207844,-0.342338,-0.003199,0.001844,-0.458554,-0.207678,-0.094913,-0.413894,0.001786,6
3,-0.019076,-0.001151,0.886958,-0.167679,-0.044414,-0.044414,-0.127353,0,0,0,...,-0.207844,-0.309219,-0.009786,0.001844,-0.361800,-0.207678,-0.094913,-0.413894,0.001786,21
4,-0.019816,-0.166050,-0.330410,-0.031437,-0.090977,-0.090977,-0.127353,0,1,0,...,-0.063689,-0.276596,-0.012291,0.001844,-0.205705,-0.063407,-0.085594,0.401554,0.001786,19